### ISSUE TITLE
can't spawn Zombie Yeti and Bungee Zombie

### ISSUE THREAD

**Issue by bongboa** [lmintlcx/pvztools#3]
Hi,
I can't spawn Zombie Yeti and Bungee Zombie, pls fix these issues?
And can you add the features: choose the lanes when spawning zombies?
 https://github.com/IntelOrca/PVZTools/releases
can you add Dr zomboss, ZomBotany zombies?

**Comment by lmintlcx** [comment]
Sure it can, only has limited count or showed in specific wave.
No, I don't know how to control which lane they appear.
Maybe you can switch to Spawn Detailed Mode ?

**Comment by bongboa** [comment]
Yes, thank you it's worked. I can spawn Zombie Yeti  Dr zomboss, ZomBotany zombies Bungee Zombie on Spawn Detailed Mode but can't find the control to choose the lanes. 
Can you add the feature: choose all plants can attack at any lane like cattail?

**Comment by lmintlcx** [comment]
No, use PVZ Helper instead.
https://pan.baidu.com/s/130HsrSOhnzJodz37jMIVwA  kur4

**Comment by bongboa** [comment]
thank you, this tool can help all plants attack at any lane?
